### ISSUE TITLE
Serving off of http during local development is not possible

### ISSUE THREAD

**Issue by anonrose** [looker-open-source/embed-sdk#10]
Due to the hard coding of [https](https://github.com/looker-open-source/embed-sdk/blob/ab5e3045d161b98f820f8baf143034de832c05b8/src/embed.ts#L73) @looker/chatty will not allow "valid messages" to be sent to the listener unless that listener is on https. 

It seems like this framework is assuming that end users will have their API host on the same domain as their looker instance. We are not doing so, and it would be nice to have a way to specify the local URL which the iframe is sitting on, and the API endpoint that is being interacted with to "sign" the iframe URLs.

**Comment by elimenko** [comment]
I'm having similar issue, the only workaround that I found is to fork `embed-sdk` and use `apiHost` as part of URL

**Comment by whscullin** [comment]
I generally would recommend serving over https even locally since it will highlight issues that a non-secure context will not, but I will expand the apiHost to accept http and https URLs.
