### ISSUE TITLE
[Feature request] Ability to send headers like params in the request to SSO server

### ISSUE THREAD

**Issue by ten-sis** [looker-open-source/embed-sdk#14]
Due to security, SSO endpoints might be hidden from public access, and as an example, JWT can be passed in headers in order to get access to the SSO server.
There is currently already a [hardcoded cache-control header](https://github.com/looker-open-source/embed-sdk/blob/master/src/embed.ts#L96). Would be great if it's possible to pass headers in the same manner as params or filters to LookerEmbedSDK

**Comment by whscullin** [comment]
This is reasonable, I will include this in an upcoming release.

**Comment by khoa-rapidai** [comment]
@whscullin I had a fix for this but couldn't have permission to push. Can you add me so that I could create a pull request for your review? Thanks!

**Comment by whscullin** [comment]
Hi! I can't add you to the looker org but if you fork you can open a PR.

**Comment by khoadp** [comment]
@whscullin Please review my PR: https://github.com/looker-open-source/embed-sdk/pull/60 . Thanks!
