### ISSUE TITLE
Embed SDK throws "Argument not optional" exception in IE11 on connect

### ISSUE THREAD

**Issue by studouglas-scx** [looker-open-source/embed-sdk#16]
We recently noticed that embedded dashboards fail to load at all in IE11 -- the connect() call throws "Argument not optional". The dashboards work fine in Chrome, Safari and Firefox.

We're using version 1.0.0-beta.3 of the sdk (though the issue also occurred on beta.2).

Usage:
```
LookerEmbedSDK.createDashboardWithId(lookerId)
            .appendTo(`#${PARENT_ID}`)
            .build()
            .connect()
            .catch(e => {
                console.error(e); // logs exception with message "Argument not optional"
            });
```

The stack trace with the error seems to point back to `embed.ts#71 (stack trace points to our internal minified file though so it may not be exact):
```
this._host = this._hostBuilder
      // tslint:disable-next-line:deprecation
      .frameBorder(this._builder.frameBorder)
      .withTargetOrigin(`https://${this._builder.apiHost}`)
      .appendTo(this._builder.el)
      .build()
```

I did see that IE11 isn't a first-class supported browser anymore (https://help.looker.com/hc/en-us/articles/360033830314), but the post seemed to indicate that iframe embedding should work (albeit slowly).

Let me know how I can help dig into this.

**Comment by whscullin** [comment]
It looks like this is related to IE `classList.add()` being called with no arguments. This will be fixed in the next release, but for now using a placeholder class with `.withClassName()` will avoid the exception.

**Comment by studouglas-scx** [comment]
Nice find, workaround works great. Thank you!
