### ISSUE TITLE
best practice for reacting to third party cookie errors

### ISSUE THREAD

**Issue by dwalker-va** [looker-open-source/embed-sdk#174]
I was wondering if there was a best practice for reacting to third party cookie errors, as the error message served by the embedded content is not helpful in this context.

<img width="659" alt="Screen Shot 2023-11-20 at 3 27 38 PM" src="https://github.com/looker-open-source/embed-sdk/assets/7460285/bb72efdc-0a97-4af5-b44c-4ce318b42d54">

It's one of those situations where yes is 100% true, but also given the context that my application has, that my organization has about how often bugs reported about this message end up being related to the client's browser blocking third party cookies, I would like my application to react and offer a little more instruction so that the user can self-serve and fix their issue.

I would have thought that
```
LookerEmbedSDK.createDashboardWithId(id)
      .withNext()
      .withDialogScroll()
      .withScrollMonitor()
      .withAllowAttr('fullscreen')
      .appendTo(target)
      .withDynamicIFrameHeight()
      .withClassName('looker-embed')
      .build()
      .connect()
      .then(() => {
        this.dashboardLoaded = true;
      })
      .catch((error: Error) => { // important bit
        this.handleLookerSDKError(error);
      });
```

would be enough to give my application a hint as to when this happened. In `handleLookerSDKError` I could set a variable that my application could observe and show a different/complementary message, hide the iframe, etc. In testing though, this doesn't work when the embedded page fails to load because the user's browser has blocked third party cookies - the `catch` block receives no error and what we see in the console is an error being logged in Looker's javascript (as in, javascript _inside_ the iframe) instead of it being piped back through here. Maybe that isn't part of this call and it's happening afterwards? How should I handle that? The `session:status` event is also not helpful in this regard, in my testing it's not being fired in such a situation.

**Comment by dwalker-va** [comment]
Thanks @fabio-looker 

In our case, we wanting to use this looker instance across multiple domains. Our customers are able to configure our software to serve it through their own custom domain, so putting our Looker instance on to a particular domain is only helpful for the portion of customers who aren't configuring a custom domain. I was hoping I would have a hook on the client side of the SDK to deal with this kind of error in a more user-friendly way. It does sound like the recommended course of action is "use cookieless embed" instead.

**Comment by fabio-looker** [comment]
Yes, for an unknown set of parent domains, Cookieless Embed will be the necessary solution (though more work to implement of course)
