### ISSUE TITLE
Cookieless acquire call produces 404

### ISSUE THREAD

**Issue by tomsseisums** [looker-open-source/embed-sdk#192]
Having set the `clientId` and `clientSecret` in the `.env` and enabled the `Use cookieless`, I get the following error:
```bash
embed session acquire failed {
  error: LookerSDKError: POST https://<redacted>.cloud.looker.com/api/4.0/embed/cookieless_session/acquire: 404 - {"message":"The resource you're looking for could not be found"}
      at new LookerSDKError (/Users/tomsseisums/Projects/<redacted>/looker-embed-sdk/node_modules/@looker/sdk-rtl/src/lookerSDKError.ts:112:11)
      at sdkError (/Users/tomsseisums/Projects/<redacted>/looker-embed-sdk/node_modules/@looker/sdk-rtl/src/transport.ts:491:14)
      at /Users/tomsseisums/Projects/<redacted>/looker-embed-sdk/node_modules/@looker/sdk-rtl/src/transport.ts:539:11
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/Users/tomsseisums/Projects/<redacted>/looker-embed-sdk/node_modules/@looker/sdk-rtl/src/transport.ts:32:50)
      at _next (/Users/tomsseisums/Projects/<redacted>/looker-embed-sdk/node_modules/@looker/sdk-rtl/src/transport.ts:32:50)
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    errors: [],
    documentation_url: ''
  }
}
```

Tried the requests in Embedded API Explorer and everything worked as expected, but I noticed that is calling `/api/internal/4.0`.

This is for the first attempt to load, not a subsequent request, where `session_reference_token` is null.

I'm using Looker (original), `24.14.20`.

This is the `demo_user.json` content:
```json
{
  "external_user_id": "user1111",
  "first_name": "Pat",
  "last_name": "Embed",
  "session_length": 10,
  "force_logout_login": true,
  "external_group_id": "group1",
  "group_ids": [],
  "permissions": [
    "access_data",
    "see_looks",
    "see_user_dashboards",
    "save_content",
    "download_without_limit",
    "create_alerts"
  ],
  "models": [
    "orders"
  ]
}
```

I'm out of clues why it's producing 404.

**Comment by tomsseisums** [comment]
Found my issue:
> "To use either API, the embedding application must be able to authenticate into the Looker API with admin privileges."

_via [https://cloud.google.com/looker/docs/cookieless-embed](https://cloud.google.com/looker/docs/cookieless-embed#:~:text=To%20use%20either%20API%2C%20the%20embedding%20application%20must%20be%20able%20to%20authenticate%20into%20the%20Looker%20API%20with%20admin%20privileges.)_

**Comment by DanUnited** [comment]
@tomsseisums have you managed to implement fully cookieless-embed on different domains?
I'm still encountering the issue with tokens, maybe I missed something that you did successfully 

https://github.com/looker-open-source/embed-sdk/issues/216
