### ISSUE TITLE
createSignedUrl doesn't handle optional parameters like first_name, last_name 

### ISSUE THREAD

**Issue by Mike-Gibson** [looker-open-source/embed-sdk#5]
Hi, I tried using the `createSignedUrl` method included in server_utils and noticed that it doesn't seem to handle not specifying the optional fields of the `user: LookerEmbedUser` argument.

When I generate a signed URL without specifying, e.g. `first_name` the URL doesn't work, and checking in the Embed URI validator in Looker gives:
> 'first_name' param cannot be parsed from JSON: 'undefined'

It seems that if an optional field is not specified it should not be JSON encoded and used in either the signing or parameters of the URL.

I'm using version 1.0.0-beta.1. Let me know if you need any more information.

**Comment by whscullin** [comment]
Thank you for the report, I am able to reproduce the issue. I hope to have a fix out shortly.
