### ISSUE TITLE
Need `withCredentials` option for CORS auth requests to function properly

### ISSUE THREAD

**Issue by brettjonesdev** [looker-open-source/embed-sdk#67]
I'm using the `LookerEmbedSDK` to embed iframes in a web application in which the frontend hangs off of a different domain/port than the backend API where my Auth endpoint lives. Currently, the `XmlHttpRequest` which the Embed SDK creates to perform the authorization call is not setting `xhr.withCredentials = true`. 

Consequently, the CORS request from `frontend.com` to `backend.com/looker/auth` is missing authorization headers (those set via Http Only cookies), which prevents my backend from being able to authenticate the User and generate the Signed SSO Embed URL correctly. This only affects CORS auth endpoints, since Http Only cookies are sent on non-CORS requests to the host's domain. 

In order to fix this, the `xhr` either needs to set `withCredentials = true` by default, *or* we need a new option in the `init()` method which will allow the user to specify the `withCredentials` boolean. I'm unsure of the security implications of the first option.

**Comment by colin-roy-ehri** [comment]
Looks like this fix would be useful for local testing of apps with the SDK.

**Comment by izzymiller** [comment]
Fixed by #68 :) thx Brett!
